services:
  api:
    build: .
    container_name: aerolineas-api
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: aerolineas-db
    restart: always
    environment:
      POSTGRES_DB: aerolineas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
